# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "users" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"email" VARCHAR NOT NULL,"name" VARCHAR NOT NULL);
create unique index "idx_users_unq_1" on "users" ("email");

# --- !Downs

drop table "users";

